AWSTemplateFormatVersion: 2010-09-09
Description: An CloudFormation template for creating a secret. Creates AppDynamics account access key secret.
Parameters:
  AppdAccountSecretKey:
    Type: String
    Default: cdd4d5d3-ac1b-4101-a934-ad72fba37f31
  AppdSecretName:
    Type: String
    Default: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
Resources:
  #This is a Secret resource with a randomly generated password in its SecretString JSON.
  AppdAccessKeySecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Ref AppdSecretName
      Description: "AppDynamics controller's secret access key"
      SecretString: !Ref AppdAccountSecretKey
Outputs:
  AppdSecretArn:
    Description: AppDynamics controller secret
    Value: !Ref AppdAccessKeySecret
